# encoding: utf-8
Country.find_by_code('us').translate_to('zh', :slug => '美国', :name => '美国', :full_name => '美利坚合众国', :searchable => 'meiguo')
Country.find_by_code('cn').translate_to('zh', :slug => '中国', :name => '中国', :full_name => '中华人民共和国', :searchable => 'zhongguo')

Country.find_by_code('af').translate_to('zh', :slug => '阿富汗', :name => '阿富汗', :full_name => '阿富汗伊斯兰共和国')
Country.find_by_code('al').translate_to('zh', :slug => '阿尔巴尼亚', :name => '阿尔巴尼亚', :full_name => '阿尔巴尼亚共和国')
Country.find_by_code('dz').translate_to('zh', :slug => '阿尔及利亚', :name => '阿尔及利亚', :full_name => '阿尔及利亚人民民主共和国')
Country.find_by_code('ad').translate_to('zh', :slug => '安道尔', :name => '安道尔', :full_name => '安道尔公国')
Country.find_by_code('ao').translate_to('zh', :slug => '安哥拉', :name => '安哥拉', :full_name => '安哥拉共和国')
Country.find_by_code('ag').translate_to('zh', :slug => '安提瓜和巴布达', :name => '安提瓜和巴布达')
Country.find_by_code('ar').translate_to('zh', :slug => '阿根廷', :name => '阿根廷', :full_name => '阿根廷共和国')
Country.find_by_code('am').translate_to('zh', :slug => '亚美尼亚', :name => '亚美尼亚', :full_name => '亚美尼亚共和国')
Country.find_by_code('au').translate_to('zh', :slug => '澳大利亚', :name => '澳大利亚', :full_name => '澳大利亚联邦')
Country.find_by_code('at').translate_to('zh', :slug => '奥地利', :name => '奥地利', :full_name => '奥地利共和国')
Country.find_by_code('az').translate_to('zh', :slug => '阿塞拜疆', :name => '阿塞拜疆', :full_name => '阿塞拜疆共和国')
Country.find_by_code('bs').translate_to('zh', :slug => '巴哈马', :name => '巴哈马', :full_name => '巴哈马国')
Country.find_by_code('bh').translate_to('zh', :slug => '巴林', :name => '巴林', :full_name => '巴林王国')
Country.find_by_code('bd').translate_to('zh', :slug => '孟加拉', :name => '孟加拉', :full_name => '孟加拉国')
Country.find_by_code('bb').translate_to('zh', :slug => '巴巴多斯', :name => '巴巴多斯')
Country.find_by_code('by').translate_to('zh', :slug => '白俄罗斯', :name => '白俄罗斯', :full_name => '白俄罗斯共和国')
Country.find_by_code('be').translate_to('zh', :slug => '比利时', :name => '比利时', :full_name => '比利时王国')
Country.find_by_code('bz').translate_to('zh', :slug => '伯利兹', :name => '伯利兹')
Country.find_by_code('bj').translate_to('zh', :slug => '贝宁', :name => '贝宁', :full_name => '贝宁共和国')
Country.find_by_code('bt').translate_to('zh', :slug => '不丹', :name => '不丹', :full_name => '不丹王国')
Country.find_by_code('bo').translate_to('zh', :slug => '玻利维亚', :name => '玻利维亚', :full_name => '玻利维亚多民族国')
Country.find_by_code('ba').translate_to('zh', :slug => '波黑', :name => '波黑', :full_name => '波斯尼亚和黑塞哥维那')
Country.find_by_code('bw').translate_to('zh', :slug => '博茨瓦纳', :name => '博茨瓦纳', :full_name => '博茨瓦纳共和国')
Country.find_by_code('br').translate_to('zh', :slug => '巴西', :name => '巴西', :full_name => '巴西联邦共和国')
Country.find_by_code('bn').translate_to('zh', :slug => '文莱', :name => '文莱', :full_name => '文莱达鲁萨兰国')
Country.find_by_code('bg').translate_to('zh', :slug => '保加利亚', :name => '保加利亚', :full_name => '保加利亚共和国')
Country.find_by_code('bf').translate_to('zh', :slug => '布基纳法索', :name => '布基纳法索', :full_name => '美利坚合众国')
Country.find_by_code('mm').translate_to('zh', :slug => '缅甸', :name => '缅甸', :full_name => '缅甸联邦共和国')
Country.find_by_code('bi').translate_to('zh', :slug => '布隆迪', :name => '布隆迪', :full_name => '布隆迪共和国')
Country.find_by_code('kh').translate_to('zh', :slug => '柬埔寨', :name => '柬埔寨', :full_name => '柬埔寨王国')
Country.find_by_code('cm').translate_to('zh', :slug => '喀麦隆', :name => '喀麦隆', :full_name => '喀麦隆共和国')
Country.find_by_code('ca').translate_to('zh', :slug => '加拿大', :name => '加拿大')
Country.find_by_code('cv').translate_to('zh', :slug => '佛得角', :name => '佛得角', :full_name => '佛得角共和国')
Country.find_by_code('cf').translate_to('zh', :slug => '中非共和国', :name => '中非共和国')
Country.find_by_code('td').translate_to('zh', :slug => '乍得', :name => '乍得', :full_name => '乍得共和国')
Country.find_by_code('cl').translate_to('zh', :slug => '智利', :name => '智利', :full_name => '智利共和国')
Country.find_by_code('co').translate_to('zh', :slug => '哥伦比亚', :name => '哥伦比亚', :full_name => '哥伦比亚共和国')
Country.find_by_code('km').translate_to('zh', :slug => '科摩罗', :name => '科摩罗', :full_name => '科摩罗联盟')
Country.find_by_code('cd').translate_to('zh', :slug => '刚果（金）', :name => '刚果（金）', :full_name => '刚果民主共和国')
Country.find_by_code('cg').translate_to('zh', :slug => '刚果（布）', :name => '刚果（布）', :full_name => '刚果共和国')
Country.find_by_code('cr').translate_to('zh', :slug => '哥斯达黎加', :name => '哥斯达黎加', :full_name => '哥斯达黎加共和国')
Country.find_by_code('ci').translate_to('zh', :slug => '科特迪瓦', :name => '科特迪瓦', :full_name => '科特迪瓦共和国')
Country.find_by_code('hr').translate_to('zh', :slug => '克罗地亚', :name => '克罗地亚', :full_name => '克罗地亚共和国')
Country.find_by_code('cu').translate_to('zh', :slug => '古巴', :name => '古巴', :full_name => '古巴共和国')
Country.find_by_code('cy').translate_to('zh', :slug => '塞浦路斯', :name => '塞浦路斯', :full_name => '塞浦路斯共和国')
Country.find_by_code('cz').translate_to('zh', :slug => '捷克', :name => '捷克', :full_name => '捷克共和国')
Country.find_by_code('dk').translate_to('zh', :slug => '丹麦', :name => '丹麦', :full_name => '丹麦王国')
Country.find_by_code('dj').translate_to('zh', :slug => '吉布提', :name => '吉布提', :full_name => '吉布提共和国')
Country.find_by_code('dm').translate_to('zh', :slug => '多米尼克', :name => '多米尼克', :full_name => '多米尼克国')
Country.find_by_code('do').translate_to('zh', :slug => '多米尼加', :name => '多米尼加', :full_name => '多米尼加共和国')
Country.find_by_code('tl').translate_to('zh', :slug => '东帝汶', :name => '东帝汶', :full_name => '东帝汶民主共和国')
Country.find_by_code('ec').translate_to('zh', :slug => '厄瓜多尔', :name => '厄瓜多尔', :full_name => '厄瓜多尔共和国')
Country.find_by_code('eg').translate_to('zh', :slug => '埃及', :name => '埃及', :full_name => '阿拉伯埃及共和国')
Country.find_by_code('sv').translate_to('zh', :slug => '萨尔瓦多', :name => '萨尔瓦多', :full_name => '萨尔瓦多共和国')
Country.find_by_code('gq').translate_to('zh', :slug => '赤道几内亚', :name => '赤道几内亚', :full_name => '赤道几内亚共和国')
Country.find_by_code('er').translate_to('zh', :slug => '厄立特里亚', :name => '厄立特里亚', :full_name => '厄立特里亚国')
Country.find_by_code('ee').translate_to('zh', :slug => '爱沙尼亚', :name => '爱沙尼亚', :full_name => '爱沙尼亚共和国')
Country.find_by_code('eh').translate_to('zh', :slug => '西撒哈拉', :name => '西撒哈拉', :full_name => '阿拉伯撒哈拉民主共和国', :alias => '主权存在争议')
Country.find_by_code('et').translate_to('zh', :slug => '埃塞俄比亚', :name => '埃塞俄比亚', :full_name => '埃塞俄比亚联邦民主共和国')
Country.find_by_code('fi').translate_to('zh', :slug => '芬兰', :name => '芬兰', :full_name => '芬兰共和国')
Country.find_by_code('fj').translate_to('zh', :slug => '斐济', :name => '斐济', :full_name => '斐济共和国')
Country.find_by_code('fk').translate_to('zh', :slug => '马尔维纳斯群岛', :name => '马尔维纳斯群岛')
Country.find_by_code('fr').translate_to('zh', :slug => '法国', :name => '法国', :full_name => '法兰西共和国')
Country.find_by_code('ga').translate_to('zh', :slug => '加蓬', :name => '加蓬', :full_name => '加蓬共和国')
Country.find_by_code('gm').translate_to('zh', :slug => '冈比亚', :name => '冈比亚', :full_name => '冈比亚共和国')
Country.find_by_code('ge').translate_to('zh', :slug => '格鲁吉亚', :name => '格鲁吉亚')
Country.find_by_code('de').translate_to('zh', :slug => '德国', :name => '德国', :full_name => '德意志联邦共和国')
Country.find_by_code('gh').translate_to('zh', :slug => '加纳', :name => '加纳', :full_name => '加纳共和国')
Country.find_by_code('gr').translate_to('zh', :slug => '希腊', :name => '希腊', :full_name => '希腊共和国')
Country.find_by_code('gd').translate_to('zh', :slug => '格林纳达', :name => '格林纳达')
Country.find_by_code('gt').translate_to('zh', :slug => '危地马拉', :name => '危地马拉', :full_name => '危地马拉共和国')
Country.find_by_code('gl').translate_to('zh', :slug => '格陵兰', :name => '格陵兰')
Country.find_by_code('gn').translate_to('zh', :slug => '几内亚', :name => '几内亚', :full_name => '几内亚共和国')
Country.find_by_code('gw').translate_to('zh', :slug => '几内亚比绍', :name => '几内亚比绍', :full_name => '几内亚比绍共和国')
Country.find_by_code('gy').translate_to('zh', :slug => '圭亚那', :name => '圭亚那', :full_name => '圭亚那合作共和国')
Country.find_by_code('ht').translate_to('zh', :slug => '海地', :name => '海地', :full_name => '海地共和国')
Country.find_by_code('hn').translate_to('zh', :slug => '洪都拉斯', :name => '洪都拉斯', :full_name => '洪都拉斯共和国')
Country.find_by_code('hk').translate_to('zh', :slug => '香港', :name => '香港', :full_name => '中华人民共和国香港特别行政区')
Country.find_by_code('hu').translate_to('zh', :slug => '匈牙利', :name => '匈牙利')
Country.find_by_code('is').translate_to('zh', :slug => '冰岛', :name => '冰岛', :full_name => '冰岛共和国')
Country.find_by_code('in').translate_to('zh', :slug => '印度', :name => '印度', :full_name => '印度共和国')
Country.find_by_code('id').translate_to('zh', :slug => '印尼', :name => '印度尼西亚', :full_name => '印度尼西亚共和国')
Country.find_by_code('ir').translate_to('zh', :slug => '伊朗', :name => '伊朗', :full_name => '伊朗伊斯兰共和国')
Country.find_by_code('iq').translate_to('zh', :slug => '伊拉克', :name => '伊拉克', :full_name => '伊拉克共和国')
Country.find_by_code('ie').translate_to('zh', :slug => '爱尔兰', :name => '爱尔兰', :full_name => '爱尔兰共和国')
Country.find_by_code('il').translate_to('zh', :slug => '以色列', :name => '以色列', :full_name => '以色列国')
Country.find_by_code('it').translate_to('zh', :slug => '意大利', :name => '意大利', :full_name => '意大利共和国')
Country.find_by_code('jm').translate_to('zh', :slug => '牙买加', :name => '牙买加')
Country.find_by_code('jp').translate_to('zh', :slug => '日本', :name => '日本', :full_name => '日本国')
Country.find_by_code('jo').translate_to('zh', :slug => '约旦', :name => '约旦', :full_name => '约旦哈希姆王国')
Country.find_by_code('kz').translate_to('zh', :slug => '哈萨克斯坦', :name => '哈萨克斯坦', :full_name => '哈萨克斯坦共和国')
Country.find_by_code('ke').translate_to('zh', :slug => '肯尼亚', :name => '肯尼亚', :full_name => '肯尼亚共和国')
Country.find_by_code('ki').translate_to('zh', :slug => '基里巴斯', :name => '基里巴斯', :full_name => '基里巴斯共和国')
Country.find_by_code('kp').translate_to('zh', :slug => '朝鲜', :name => '朝鲜', :full_name => '朝鲜民主主义人民共和国')
Country.find_by_code('kr').translate_to('zh', :slug => '韩国', :name => '韩国', :full_name => '大韩民国')
Country.find_by_code('xk').translate_to('zh', :slug => '科索沃', :name => '科索沃', :full_name => '科索沃共和国')
Country.find_by_code('kw').translate_to('zh', :slug => '科威特', :name => '科威特', :full_name => '科威特国')
Country.find_by_code('kg').translate_to('zh', :slug => '吉尔吉斯斯坦', :name => '吉尔吉斯斯坦', :full_name => '吉尔吉斯斯坦共和国')
Country.find_by_code('la').translate_to('zh', :slug => '老挝', :name => '老挝', :full_name => '老挝人民民主共和国')
Country.find_by_code('lv').translate_to('zh', :slug => '拉脱维亚', :name => '拉脱维亚', :full_name => '拉脱维亚共和国')
Country.find_by_code('lb').translate_to('zh', :slug => '黎巴嫩', :name => '黎巴嫩', :full_name => '黎巴嫩共和国')
Country.find_by_code('ls').translate_to('zh', :slug => '莱索托', :name => '莱索托', :full_name => '莱索托王国')
Country.find_by_code('lr').translate_to('zh', :slug => '利比里亚', :name => '利比里亚', :full_name => '利比里亚共和国')
Country.find_by_code('ly').translate_to('zh', :slug => '利比亚', :name => '利比亚', :full_name => '利比亚国')
Country.find_by_code('li').translate_to('zh', :slug => '列支敦士登', :name => '列支敦士登', :full_name => '列支敦士登公国')
Country.find_by_code('lt').translate_to('zh', :slug => '立陶宛', :name => '立陶宛', :full_name => '立陶宛共和国')
Country.find_by_code('lu').translate_to('zh', :slug => '卢森堡', :name => '卢森堡', :full_name => '卢森堡大公国')
Country.find_by_code('mo').translate_to('zh', :slug => '澳门', :name => '澳门', :full_name => '中华人民共和国澳门特别行政区')
Country.find_by_code('mk').translate_to('zh', :slug => '马其顿', :name => '马其顿', :full_name => '马其顿共和国')
Country.find_by_code('mg').translate_to('zh', :slug => '马达加斯加', :name => '马达加斯加', :full_name => '马达加斯加共和国')
Country.find_by_code('mw').translate_to('zh', :slug => '马拉维', :name => '马拉维', :full_name => '马拉维共和国')
Country.find_by_code('my').translate_to('zh', :slug => '马来西亚', :name => '马来西亚', :full_name => '马来西亚联邦')
Country.find_by_code('mv').translate_to('zh', :slug => '马尔代夫', :name => '马尔代夫', :full_name => '马尔代夫共和国')
Country.find_by_code('ml').translate_to('zh', :slug => '马里', :name => '马里', :full_name => '马里共和国')
Country.find_by_code('mt').translate_to('zh', :slug => '马耳他', :name => '马耳他', :full_name => '马耳他共和国')
Country.find_by_code('mh').translate_to('zh', :slug => '马绍尔群岛', :name => '马绍尔群岛', :full_name => '马绍尔群岛共和国')
Country.find_by_code('mr').translate_to('zh', :slug => '毛里塔尼亚', :name => '毛里塔尼亚', :full_name => '毛里塔尼亚伊斯兰共和国')
Country.find_by_code('mu').translate_to('zh', :slug => '毛里求斯', :name => '毛里求斯', :full_name => '毛里求斯共和国')
Country.find_by_code('mx').translate_to('zh', :slug => '墨西哥', :name => '墨西哥', :full_name => '墨西哥合众国')
Country.find_by_code('fm').translate_to('zh', :slug => '密克罗尼西亚联邦', :name => '密克罗尼西亚联邦')
Country.find_by_code('md').translate_to('zh', :slug => '摩尔多瓦', :name => '摩尔多瓦', :full_name => '摩尔多瓦共和国')
Country.find_by_code('mc').translate_to('zh', :slug => '摩纳哥', :name => '摩纳哥', :full_name => '摩纳哥公国')
Country.find_by_code('mn').translate_to('zh', :slug => '蒙古', :name => '蒙古', :full_name => '蒙古国')
Country.find_by_code('me').translate_to('zh', :slug => '黑山', :name => '黑山', :full_name => '黑山共和国')
Country.find_by_code('ma').translate_to('zh', :slug => '摩洛哥', :name => '摩洛哥', :full_name => '摩洛哥王国')
Country.find_by_code('mz').translate_to('zh', :slug => '莫桑比克', :name => '莫桑比克', :full_name => '莫桑比克共和国')
Country.find_by_code('na').translate_to('zh', :slug => '纳米比亚', :name => '纳米比亚', :full_name => '纳米比亚共和国')
Country.find_by_code('nr').translate_to('zh', :slug => '瑙鲁', :name => '瑙鲁', :full_name => '瑙鲁共和国')
Country.find_by_code('np').translate_to('zh', :slug => '尼泊尔', :name => '尼泊尔', :full_name => '尼泊尔联邦民主共和国')
Country.find_by_code('nl').translate_to('zh', :slug => '荷兰', :name => '荷兰', :full_name => '尼德兰王国')
Country.find_by_code('nz').translate_to('zh', :slug => '新西兰', :name => '新西兰')
Country.find_by_code('ni').translate_to('zh', :slug => '尼加拉瓜', :name => '尼加拉瓜', :full_name => '尼加拉瓜共和国')
Country.find_by_code('ne').translate_to('zh', :slug => '尼日尔', :name => '尼日尔', :full_name => '尼日尔共和国')
Country.find_by_code('ng').translate_to('zh', :slug => '尼日利亚', :name => '尼日利亚', :full_name => '尼日利亚联邦共和国')
Country.find_by_code('nc').translate_to('zh', :slug => '新喀里多尼亚', :name => '新喀里多尼亚')
Country.find_by_code('nc1').translate_to('zh', :slug => '北塞浦路斯', :name => '北塞浦路斯', :full_name => '北塞浦路斯土耳其共和国', :alias => '主权存在争议')
Country.find_by_code('no').translate_to('zh', :slug => '挪威', :name => '挪威', :full_name => '挪威王国')
Country.find_by_code('om').translate_to('zh', :slug => '阿曼', :name => '阿曼', :full_name => '阿曼苏丹国')
Country.find_by_code('ps').translate_to('zh', :slug => '巴勒斯坦', :name => '巴勒斯坦', :full_name => '巴勒斯坦国', :alias => '主权存在争议')
Country.find_by_code('pk').translate_to('zh', :slug => '巴基斯坦', :name => '巴基斯坦', :full_name => '巴基斯坦伊斯兰共和国')
Country.find_by_code('pw').translate_to('zh', :slug => '帕劳', :name => '帕劳', :full_name => '帕劳共和国')
Country.find_by_code('pa').translate_to('zh', :slug => '巴拿马', :name => '巴拿马', :full_name => '巴拿马共和国')
Country.find_by_code('pg').translate_to('zh', :slug => '巴布亚新几内亚', :name => '巴布亚新几内亚', :full_name => '巴布亚新几内亚独立国')
Country.find_by_code('py').translate_to('zh', :slug => '巴拉圭', :name => '巴拉圭', :full_name => '巴拉圭共和国')
Country.find_by_code('pe').translate_to('zh', :slug => '秘鲁', :name => '秘鲁', :full_name => '秘鲁共和国')
Country.find_by_code('ph').translate_to('zh', :slug => '菲律宾', :name => '菲律宾', :full_name => '菲律宾共和国')
Country.find_by_code('pl').translate_to('zh', :slug => '波兰', :name => '波兰', :full_name => '波兰共和国')
Country.find_by_code('pt').translate_to('zh', :slug => '葡萄牙', :name => '葡萄牙', :full_name => '葡萄牙共和国')
Country.find_by_code('pr').translate_to('zh', :slug => '波多黎各', :name => '波多黎各', :full_name => '波多黎各自治邦')
Country.find_by_code('qa').translate_to('zh', :slug => '卡塔尔', :name => '卡塔尔', :full_name => '卡塔尔国')
Country.find_by_code('ro').translate_to('zh', :slug => '罗马尼亚', :name => '罗马尼亚')
Country.find_by_code('ru').translate_to('zh', :slug => '俄罗斯', :name => '俄罗斯', :full_name => '俄罗斯联邦')
Country.find_by_code('rw').translate_to('zh', :slug => '卢旺达', :name => '卢旺达', :full_name => '卢旺达共和国')
Country.find_by_code('kn').translate_to('zh', :slug => '圣克里斯多福与尼维斯', :name => '圣克里斯多福与尼维斯', :full_name => '圣克里斯多福与尼维斯联邦')
Country.find_by_code('lc').translate_to('zh', :slug => '圣卢西亚', :name => '圣卢西亚')
Country.find_by_code('vc').translate_to('zh', :slug => '圣文森特和格林纳丁斯', :name => '圣文森特和格林纳丁斯')
Country.find_by_code('ws').translate_to('zh', :slug => '萨摩亚', :name => '萨摩亚', :full_name => '萨摩亚独立国')
Country.find_by_code('sm').translate_to('zh', :slug => '圣马力诺', :name => '圣马力诺', :full_name => '圣马力诺共和国')
Country.find_by_code('st').translate_to('zh', :slug => '圣多美和普林西比', :name => '圣多美和普林西比', :full_name => '圣多美和普林西比民主共和国')
Country.find_by_code('sa').translate_to('zh', :slug => '沙特阿拉伯', :name => '沙特阿拉伯', :full_name => '沙特阿拉伯王国')
Country.find_by_code('sn').translate_to('zh', :slug => '塞内加尔', :name => '塞内加尔', :full_name => '塞内加尔共和国')
Country.find_by_code('rs').translate_to('zh', :slug => '塞尔维亚', :name => '塞尔维亚', :full_name => '塞尔维亚共和国')
Country.find_by_code('sc').translate_to('zh', :slug => '塞舌尔', :name => '塞舌尔', :full_name => '塞舌尔共和国')
Country.find_by_code('sl').translate_to('zh', :slug => '塞拉利昂', :name => '塞拉利昂', :full_name => '塞拉利昂共和国')
Country.find_by_code('sg').translate_to('zh', :slug => '新加坡', :name => '新加坡', :full_name => '新加坡共和国')
Country.find_by_code('sk').translate_to('zh', :slug => '斯洛伐克', :name => '斯洛伐克', :full_name => '斯洛伐克共和国')
Country.find_by_code('si').translate_to('zh', :slug => '斯洛文尼亚', :name => '斯洛文尼亚', :full_name => '斯洛文尼亚共和国')
Country.find_by_code('sb').translate_to('zh', :slug => '所罗门群岛', :name => '所罗门群岛')
Country.find_by_code('so').translate_to('zh', :slug => '索马里', :name => '索马里', :full_name => '索马里联邦共和国')
Country.find_by_code('so1').translate_to('zh', :slug => '索马里兰', :name => '索马里兰', :full_name => '索马里兰共和国', :alias => '主权存在争议')
Country.find_by_code('za').translate_to('zh', :slug => '南非', :name => '南非', :full_name => '南非共和国')
Country.find_by_code('ss').translate_to('zh', :slug => '南苏丹', :name => '南苏丹', :full_name => '南苏丹共和国')
Country.find_by_code('es').translate_to('zh', :slug => '西班牙', :name => '西班牙', :full_name => '西班牙王国')
Country.find_by_code('lk').translate_to('zh', :slug => '斯里兰卡', :name => '斯里兰卡', :full_name => '斯里兰卡民主社会主义共和国')
Country.find_by_code('sd').translate_to('zh', :slug => '苏丹', :name => '苏丹', :full_name => '苏丹共和国')
Country.find_by_code('sr').translate_to('zh', :slug => '苏里南', :name => '苏里南', :full_name => '苏里南共和国')
Country.find_by_code('sz').translate_to('zh', :slug => '斯威士兰', :name => '斯威士兰', :full_name => '斯威士兰王国')
Country.find_by_code('se').translate_to('zh', :slug => '瑞典', :name => '瑞典', :full_name => '瑞典王国')
Country.find_by_code('ch').translate_to('zh', :slug => '瑞士', :name => '瑞士', :full_name => '瑞士联邦')
Country.find_by_code('sy').translate_to('zh', :slug => '叙利亚', :name => '叙利亚', :full_name => '阿拉伯叙利亚共和国')
Country.find_by_code('tw').translate_to('zh', :slug => '台湾', :name => '台湾', :full_name => '中华民国', :alias => '中华台北')
Country.find_by_code('tj').translate_to('zh', :slug => '塔吉克斯坦', :name => '塔吉克斯坦', :full_name => '塔吉克斯坦共和国')
Country.find_by_code('tz').translate_to('zh', :slug => '坦桑尼亚', :name => '坦桑尼亚', :full_name => '坦桑尼亚联合共和国')
Country.find_by_code('th').translate_to('zh', :slug => '泰国', :name => '泰国', :full_name => '泰王国')
Country.find_by_code('tg').translate_to('zh', :slug => '多哥', :name => '多哥', :full_name => '多哥共和国')
Country.find_by_code('to').translate_to('zh', :slug => '汤加', :name => '汤加', :full_name => '汤加王国')
Country.find_by_code('tt').translate_to('zh', :slug => '特立尼达和多巴哥', :name => '特立尼达和多巴哥', :full_name => '特立尼达和多巴哥共和国')
Country.find_by_code('tn').translate_to('zh', :slug => '突尼斯', :name => '突尼斯', :full_name => '突尼斯共和国')
Country.find_by_code('tr').translate_to('zh', :slug => '土耳其', :name => '土耳其', :full_name => '土耳其共和国')
Country.find_by_code('tm').translate_to('zh', :slug => '土库曼斯坦', :name => '土库曼斯坦')
Country.find_by_code('tv').translate_to('zh', :slug => '图瓦卢', :name => '图瓦卢')
Country.find_by_code('ug').translate_to('zh', :slug => '乌干达', :name => '乌干达', :full_name => '乌干达共和国')
Country.find_by_code('ua').translate_to('zh', :slug => '乌克兰', :name => '乌克兰')
Country.find_by_code('ae').translate_to('zh', :slug => '阿联酋', :name => '阿联酋', :full_name => '阿拉伯联合酋长国')
Country.find_by_code('gb').translate_to('zh', :slug => '英国', :name => '英国', :full_name => '大不列颠及北爱尔兰联合王国')
Country.find_by_code('uy').translate_to('zh', :slug => '乌拉圭', :name => '乌拉圭', :full_name => '乌拉圭东岸共和国')
Country.find_by_code('uz').translate_to('zh', :slug => '乌兹别克斯坦', :name => '乌兹别克斯坦', :full_name => '乌兹别克斯坦共和国')
Country.find_by_code('vu').translate_to('zh', :slug => '瓦努阿图', :name => '瓦努阿图', :full_name => '瓦努阿图共和国')
Country.find_by_code('va').translate_to('zh', :slug => '梵蒂冈', :name => '梵蒂冈', :full_name => '梵蒂冈城国')
Country.find_by_code('ve').translate_to('zh', :slug => '委内瑞拉', :name => '委内瑞拉', :full_name => '委内瑞拉玻利瓦尔共和国')
Country.find_by_code('vn').translate_to('zh', :slug => '越南', :name => '越南', :full_name => '越南社会主义共和国')
Country.find_by_code('ye').translate_to('zh', :slug => '也门', :name => '也门', :full_name => '也门共和国')
Country.find_by_code('zm').translate_to('zh', :slug => '赞比亚', :name => '赞比亚', :full_name => '赞比亚共和国')
Country.find_by_code('zw').translate_to('zh', :slug => '津巴布韦', :name => '津巴布韦', :full_name => '津巴布韦共和国')

