# encoding: utf-8

I18n.with_locale(:zh) do
  Country.find_by_code('us').update_attributes(:name => '美国', :full_name => '美利坚合众国', :searchable => 'meiguo')
  Country.find_by_code('cn').update_attributes(:name => '中国', :full_name => '中华人民共和国', :searchable => 'zhongguo')


  #TODO: add searchables in pinyin
  Country.find_by_code('af').update_attributes(:name => '阿富汗', :full_name => '阿富汗伊斯兰共和国')
  Country.find_by_code('al').update_attributes(:name => '阿尔巴尼亚', :full_name => '阿尔巴尼亚共和国')
  Country.find_by_code('dz').update_attributes(:name => '阿尔及利亚', :full_name => '阿尔及利亚人民民主共和国')
  Country.find_by_code('ad').update_attributes(:name => '安道尔', :full_name => '安道尔公国')
  Country.find_by_code('ao').update_attributes(:name => '安哥拉', :full_name => '安哥拉共和国')
  Country.find_by_code('ag').update_attributes(:name => '安提瓜和巴布达')
  Country.find_by_code('ar').update_attributes(:name => '阿根廷', :full_name => '阿根廷共和国')
  Country.find_by_code('am').update_attributes(:name => '亚美尼亚', :full_name => '亚美尼亚共和国')
  Country.find_by_code('au').update_attributes(:name => '澳大利亚', :full_name => '澳大利亚联邦')
  Country.find_by_code('at').update_attributes(:name => '奥地利', :full_name => '奥地利共和国')
  Country.find_by_code('az').update_attributes(:name => '阿塞拜疆', :full_name => '阿塞拜疆共和国')
  Country.find_by_code('bs').update_attributes(:name => '巴哈马', :full_name => '巴哈马国')
  Country.find_by_code('bh').update_attributes(:name => '巴林', :full_name => '巴林王国')
  Country.find_by_code('bd').update_attributes(:name => '孟加拉', :full_name => '孟加拉国')
  Country.find_by_code('bb').update_attributes(:name => '巴巴多斯')
  Country.find_by_code('by').update_attributes(:name => '白俄罗斯', :full_name => '白俄罗斯共和国')
  Country.find_by_code('be').update_attributes(:name => '比利时', :full_name => '比利时王国')
  Country.find_by_code('bz').update_attributes(:name => '伯利兹')
  Country.find_by_code('bj').update_attributes(:name => '贝宁', :full_name => '贝宁共和国')
  Country.find_by_code('bt').update_attributes(:name => '不丹', :full_name => '不丹王国')
  Country.find_by_code('bo').update_attributes(:name => '玻利维亚', :full_name => '玻利维亚多民族国')
  Country.find_by_code('ba').update_attributes(:name => '波黑', :full_name => '波斯尼亚和黑塞哥维那')
  Country.find_by_code('bw').update_attributes(:name => '博茨瓦纳', :full_name => '博茨瓦纳共和国')
  Country.find_by_code('br').update_attributes(:name => '巴西', :full_name => '巴西联邦共和国')
  Country.find_by_code('bn').update_attributes(:name => '文莱', :full_name => '文莱达鲁萨兰国')
  Country.find_by_code('bg').update_attributes(:name => '保加利亚', :full_name => '保加利亚共和国')
  Country.find_by_code('bf').update_attributes(:name => '布基纳法索', :full_name => '美利坚合众国')
  Country.find_by_code('mm').update_attributes(:name => '缅甸', :full_name => '缅甸联邦共和国')
  Country.find_by_code('bi').update_attributes(:name => '布隆迪', :full_name => '布隆迪共和国')
  Country.find_by_code('kh').update_attributes(:name => '柬埔寨', :full_name => '柬埔寨王国')
  Country.find_by_code('cm').update_attributes(:name => '喀麦隆', :full_name => '喀麦隆共和国')
  Country.find_by_code('ca').update_attributes(:name => '加拿大')
  Country.find_by_code('cv').update_attributes(:name => '佛得角', :full_name => '佛得角共和国')
  Country.find_by_code('cf').update_attributes(:name => '中非共和国')
  Country.find_by_code('td').update_attributes(:name => '乍得', :full_name => '乍得共和国')
  Country.find_by_code('cl').update_attributes(:name => '智利', :full_name => '智利共和国')
  Country.find_by_code('co').update_attributes(:name => '哥伦比亚', :full_name => '哥伦比亚共和国')
  Country.find_by_code('km').update_attributes(:name => '科摩罗', :full_name => '科摩罗联盟')
  Country.find_by_code('cd').update_attributes(:name => '刚果（金）', :full_name => '刚果民主共和国', :pretty_name => '刚果（金）')
  Country.find_by_code('cg').update_attributes(:name => '刚果（布）', :full_name => '刚果共和国', :pretty_name => '刚果（布）')
  Country.find_by_code('cr').update_attributes(:name => '哥斯达黎加', :full_name => '哥斯达黎加共和国')
  Country.find_by_code('ci').update_attributes(:name => '科特迪瓦', :full_name => '科特迪瓦共和国')
  Country.find_by_code('hr').update_attributes(:name => '克罗地亚', :full_name => '克罗地亚共和国')
  Country.find_by_code('cu').update_attributes(:name => '古巴', :full_name => '古巴共和国')
  Country.find_by_code('cy').update_attributes(:name => '塞浦路斯', :full_name => '塞浦路斯共和国')
  Country.find_by_code('cz').update_attributes(:name => '捷克', :full_name => '捷克共和国')
  Country.find_by_code('dk').update_attributes(:name => '丹麦', :full_name => '丹麦王国')
  Country.find_by_code('dj').update_attributes(:name => '吉布提', :full_name => '吉布提共和国')
  Country.find_by_code('dm').update_attributes(:name => '多米尼克', :full_name => '多米尼克国')
  Country.find_by_code('do').update_attributes(:name => '多米尼加', :full_name => '多米尼加共和国')
  Country.find_by_code('tl').update_attributes(:name => '东帝汶', :full_name => '东帝汶民主共和国')
  Country.find_by_code('ec').update_attributes(:name => '厄瓜多尔', :full_name => '厄瓜多尔共和国')
  Country.find_by_code('eg').update_attributes(:name => '埃及', :full_name => '阿拉伯埃及共和国')
  Country.find_by_code('sv').update_attributes(:name => '萨尔瓦多', :full_name => '萨尔瓦多共和国')
  Country.find_by_code('gq').update_attributes(:name => '赤道几内亚', :full_name => '赤道几内亚共和国')
  Country.find_by_code('er').update_attributes(:name => '厄立特里亚', :full_name => '厄立特里亚国')
  Country.find_by_code('ee').update_attributes(:name => '爱沙尼亚', :full_name => '爱沙尼亚共和国')
  Country.find_by_code('eh').update_attributes(:name => '西撒哈拉', :full_name => '阿拉伯撒哈拉民主共和国', :alias => '主权存在争议')
  Country.find_by_code('et').update_attributes(:name => '埃塞俄比亚', :full_name => '埃塞俄比亚联邦民主共和国')
  Country.find_by_code('fi').update_attributes(:name => '芬兰', :full_name => '芬兰共和国')
  Country.find_by_code('fj').update_attributes(:name => '斐济', :full_name => '斐济共和国')
  Country.find_by_code('fk').update_attributes(:name => '马尔维纳斯群岛')
  Country.find_by_code('fr').update_attributes(:name => '法国', :full_name => '法兰西共和国')
  Country.find_by_code('ga').update_attributes(:name => '加蓬', :full_name => '加蓬共和国')
  Country.find_by_code('gm').update_attributes(:name => '冈比亚', :full_name => '冈比亚共和国')
  Country.find_by_code('ge').update_attributes(:name => '格鲁吉亚')
  Country.find_by_code('de').update_attributes(:name => '德国', :full_name => '德意志联邦共和国')
  Country.find_by_code('gh').update_attributes(:name => '加纳', :full_name => '加纳共和国')
  Country.find_by_code('gr').update_attributes(:name => '希腊', :full_name => '希腊共和国')
  Country.find_by_code('gd').update_attributes(:name => '格林纳达')
  Country.find_by_code('gt').update_attributes(:name => '危地马拉', :full_name => '危地马拉共和国')
  Country.find_by_code('gl').update_attributes(:name => '格陵兰')
  Country.find_by_code('gn').update_attributes(:name => '几内亚', :full_name => '几内亚共和国')
  Country.find_by_code('gw').update_attributes(:name => '几内亚比绍', :full_name => '几内亚比绍共和国')
  Country.find_by_code('gy').update_attributes(:name => '圭亚那', :full_name => '圭亚那合作共和国')
  Country.find_by_code('ht').update_attributes(:name => '海地', :full_name => '海地共和国')
  Country.find_by_code('hn').update_attributes(:name => '洪都拉斯', :full_name => '洪都拉斯共和国')
  Country.find_by_code('hk').update_attributes(:name => '香港', :full_name => '中华人民共和国香港特别行政区')
  Country.find_by_code('hu').update_attributes(:name => '匈牙利')
  Country.find_by_code('is').update_attributes(:name => '冰岛', :full_name => '冰岛共和国')
  Country.find_by_code('in').update_attributes(:name => '印度', :full_name => '印度共和国')
  Country.find_by_code('id').update_attributes(:name => '印度尼西亚', :full_name => '印度尼西亚共和国')
  Country.find_by_code('ir').update_attributes(:name => '伊朗', :full_name => '伊朗伊斯兰共和国')
  Country.find_by_code('iq').update_attributes(:name => '伊拉克', :full_name => '伊拉克共和国')
  Country.find_by_code('ie').update_attributes(:name => '爱尔兰', :full_name => '爱尔兰共和国')
  Country.find_by_code('il').update_attributes(:name => '以色列', :full_name => '以色列国')
  Country.find_by_code('it').update_attributes(:name => '意大利', :full_name => '意大利共和国')
  Country.find_by_code('jm').update_attributes(:name => '牙买加')
  Country.find_by_code('jp').update_attributes(:name => '日本', :full_name => '日本国')
  Country.find_by_code('jo').update_attributes(:name => '约旦', :full_name => '约旦哈希姆王国')
  Country.find_by_code('kz').update_attributes(:name => '哈萨克斯坦', :full_name => '哈萨克斯坦共和国')
  Country.find_by_code('ke').update_attributes(:name => '肯尼亚', :full_name => '肯尼亚共和国')
  Country.find_by_code('ki').update_attributes(:name => '基里巴斯', :full_name => '基里巴斯共和国')
  Country.find_by_code('kp').update_attributes(:name => '朝鲜', :full_name => '朝鲜民主主义人民共和国', :pretty_name => '朝鲜')
  Country.find_by_code('kr').update_attributes(:name => '韩国', :full_name => '大韩民国', :pretty_name => '韩国')
  Country.find_by_code('xk').update_attributes(:name => '科索沃', :full_name => '科索沃共和国')
  Country.find_by_code('kw').update_attributes(:name => '科威特', :full_name => '科威特国')
  Country.find_by_code('kg').update_attributes(:name => '吉尔吉斯斯坦', :full_name => '吉尔吉斯斯坦共和国')
  Country.find_by_code('la').update_attributes(:name => '老挝', :full_name => '老挝人民民主共和国')
  Country.find_by_code('lv').update_attributes(:name => '拉脱维亚', :full_name => '拉脱维亚共和国')
  Country.find_by_code('lb').update_attributes(:name => '黎巴嫩', :full_name => '黎巴嫩共和国')
  Country.find_by_code('ls').update_attributes(:name => '莱索托', :full_name => '莱索托王国')
  Country.find_by_code('lr').update_attributes(:name => '利比里亚', :full_name => '利比里亚共和国')
  Country.find_by_code('ly').update_attributes(:name => '利比亚', :full_name => '利比亚国')
  Country.find_by_code('li').update_attributes(:name => '列支敦士登', :full_name => '列支敦士登公国')
  Country.find_by_code('lt').update_attributes(:name => '立陶宛', :full_name => '立陶宛共和国')
  Country.find_by_code('lu').update_attributes(:name => '卢森堡', :full_name => '卢森堡大公国')
  Country.find_by_code('mo').update_attributes(:name => '澳门', :full_name => '中华人民共和国澳门特别行政区')
  Country.find_by_code('mk').update_attributes(:name => '马其顿', :full_name => '马其顿共和国')
  Country.find_by_code('mg').update_attributes(:name => '马达加斯加', :full_name => '马达加斯加共和国')
  Country.find_by_code('mw').update_attributes(:name => '马拉维', :full_name => '马拉维共和国')
  Country.find_by_code('my').update_attributes(:name => '马来西亚', :full_name => '马来西亚联邦')
  Country.find_by_code('mv').update_attributes(:name => '马尔代夫', :full_name => '马尔代夫共和国')
  Country.find_by_code('ml').update_attributes(:name => '马里', :full_name => '马里共和国')
  Country.find_by_code('mt').update_attributes(:name => '马耳他', :full_name => '马耳他共和国')
  Country.find_by_code('mh').update_attributes(:name => '马绍尔群岛', :full_name => '马绍尔群岛共和国')
  Country.find_by_code('mr').update_attributes(:name => '毛里塔尼亚', :full_name => '毛里塔尼亚伊斯兰共和国')
  Country.find_by_code('mu').update_attributes(:name => '毛里求斯', :full_name => '毛里求斯共和国')
  Country.find_by_code('mx').update_attributes(:name => '墨西哥', :full_name => '墨西哥合众国')
  Country.find_by_code('fm').update_attributes(:name => '密克罗尼西亚联邦')
  Country.find_by_code('md').update_attributes(:name => '摩尔多瓦', :full_name => '摩尔多瓦共和国')
  Country.find_by_code('mc').update_attributes(:name => '摩纳哥', :full_name => '摩纳哥公国')
  Country.find_by_code('mn').update_attributes(:name => '蒙古', :full_name => '蒙古国')
  Country.find_by_code('me').update_attributes(:name => '黑山', :full_name => '黑山共和国')
  Country.find_by_code('ma').update_attributes(:name => '摩洛哥', :full_name => '摩洛哥王国')
  Country.find_by_code('mz').update_attributes(:name => '莫桑比克', :full_name => '莫桑比克共和国')
  Country.find_by_code('na').update_attributes(:name => '纳米比亚', :full_name => '纳米比亚共和国')
  Country.find_by_code('nr').update_attributes(:name => '瑙鲁', :full_name => '瑙鲁共和国')
  Country.find_by_code('np').update_attributes(:name => '尼泊尔', :full_name => '尼泊尔联邦民主共和国')
  Country.find_by_code('nl').update_attributes(:name => '荷兰', :full_name => '尼德兰王国')
  Country.find_by_code('nz').update_attributes(:name => '新西兰')
  Country.find_by_code('ni').update_attributes(:name => '尼加拉瓜', :full_name => '尼加拉瓜共和国')
  Country.find_by_code('ne').update_attributes(:name => '尼日尔', :full_name => '尼日尔共和国')
  Country.find_by_code('ng').update_attributes(:name => '尼日利亚', :full_name => '尼日利亚联邦共和国')
  Country.find_by_code('nc').update_attributes(:name => '新喀里多尼亚')
  Country.find_by_code('nc1').update_attributes(:name => '北塞浦路斯', :full_name => '北塞浦路斯土耳其共和国', :pretty_name =>'北塞浦路斯', :alias => '主权存在争议')
  Country.find_by_code('no').update_attributes(:name => '挪威', :full_name => '挪威王国')
  Country.find_by_code('om').update_attributes(:name => '阿曼', :full_name => '阿曼苏丹国')
  Country.find_by_code('ps').update_attributes(:name => '巴勒斯坦', :full_name => '巴勒斯坦国', :alias => '主权存在争议')
  Country.find_by_code('pk').update_attributes(:name => '巴基斯坦', :full_name => '巴基斯坦伊斯兰共和国')
  Country.find_by_code('pw').update_attributes(:name => '帕劳', :full_name => '帕劳共和国')
  Country.find_by_code('pa').update_attributes(:name => '巴拿马', :full_name => '巴拿马共和国')
  Country.find_by_code('pg').update_attributes(:name => '巴布亚新几内亚', :full_name => '巴布亚新几内亚独立国')
  Country.find_by_code('py').update_attributes(:name => '巴拉圭', :full_name => '巴拉圭共和国')
  Country.find_by_code('pe').update_attributes(:name => '秘鲁', :full_name => '秘鲁共和国')
  Country.find_by_code('ph').update_attributes(:name => '菲律宾', :full_name => '菲律宾共和国')
  Country.find_by_code('pl').update_attributes(:name => '波兰', :full_name => '波兰共和国')
  Country.find_by_code('pt').update_attributes(:name => '葡萄牙', :full_name => '葡萄牙共和国')
  Country.find_by_code('pr').update_attributes(:name => '波多黎各', :full_name => '波多黎各自治邦')
  Country.find_by_code('qa').update_attributes(:name => '卡塔尔', :full_name => '卡塔尔国')
  Country.find_by_code('ro').update_attributes(:name => '罗马尼亚')
  Country.find_by_code('ru').update_attributes(:name => '俄罗斯', :full_name => '俄罗斯联邦')
  Country.find_by_code('rw').update_attributes(:name => '卢旺达', :full_name => '卢旺达共和国')
  Country.find_by_code('kn').update_attributes(:name => '圣克里斯多福与尼维斯', :full_name => '圣克里斯多福与尼维斯联邦')
  Country.find_by_code('lc').update_attributes(:name => '圣卢西亚')
  Country.find_by_code('vc').update_attributes(:name => '圣文森特和格林纳丁斯')
  Country.find_by_code('ws').update_attributes(:name => '萨摩亚', :full_name => '萨摩亚独立国')
  Country.find_by_code('sm').update_attributes(:name => '圣马力诺', :full_name => '圣马力诺共和国')
  Country.find_by_code('st').update_attributes(:name => '圣多美和普林西比', :full_name => '圣多美和普林西比民主共和国')
  Country.find_by_code('sa').update_attributes(:name => '沙特阿拉伯', :full_name => '沙特阿拉伯王国')
  Country.find_by_code('sn').update_attributes(:name => '塞内加尔', :full_name => '塞内加尔共和国')
  Country.find_by_code('rs').update_attributes(:name => '塞尔维亚', :full_name => '塞尔维亚共和国')
  Country.find_by_code('sc').update_attributes(:name => '塞舌尔', :full_name => '塞舌尔共和国')
  Country.find_by_code('sl').update_attributes(:name => '塞拉利昂', :full_name => '塞拉利昂共和国')
  Country.find_by_code('sg').update_attributes(:name => '新加坡', :full_name => '新加坡共和国')
  Country.find_by_code('sk').update_attributes(:name => '斯洛伐克', :full_name => '斯洛伐克共和国')
  Country.find_by_code('si').update_attributes(:name => '斯洛文尼亚', :full_name => '斯洛文尼亚共和国')
  Country.find_by_code('sb').update_attributes(:name => '所罗门群岛')
  Country.find_by_code('so').update_attributes(:name => '索马里', :full_name => '索马里联邦共和国')
  Country.find_by_code('so1').update_attributes(:name => '索马里兰', :full_name => '索马里兰共和国', :alias => '主权存在争议')
  Country.find_by_code('za').update_attributes(:name => '南非', :full_name => '南非共和国')
  Country.find_by_code('ss').update_attributes(:name => '南苏丹', :full_name => '南苏丹共和国')
  Country.find_by_code('es').update_attributes(:name => '西班牙', :full_name => '西班牙王国')
  Country.find_by_code('lk').update_attributes(:name => '斯里兰卡', :full_name => '斯里兰卡民主社会主义共和国')
  Country.find_by_code('sd').update_attributes(:name => '苏丹', :full_name => '苏丹共和国')
  Country.find_by_code('sr').update_attributes(:name => '苏里南', :full_name => '苏里南共和国')
  Country.find_by_code('sz').update_attributes(:name => '斯威士兰', :full_name => '斯威士兰王国')
  Country.find_by_code('se').update_attributes(:name => '瑞典', :full_name => '瑞典王国')
  Country.find_by_code('ch').update_attributes(:name => '瑞士', :full_name => '瑞士联邦')
  Country.find_by_code('sy').update_attributes(:name => '叙利亚', :full_name => '阿拉伯叙利亚共和国')
  Country.find_by_code('tw').update_attributes(:name => '台湾', :full_name => '中华民国', :alias => '中华台北')
  Country.find_by_code('tj').update_attributes(:name => '塔吉克斯坦', :full_name => '塔吉克斯坦共和国')
  Country.find_by_code('tz').update_attributes(:name => '坦桑尼亚', :full_name => '坦桑尼亚联合共和国')
  Country.find_by_code('th').update_attributes(:name => '泰国', :full_name => '泰王国')
  Country.find_by_code('tg').update_attributes(:name => '多哥', :full_name => '多哥共和国')
  Country.find_by_code('to').update_attributes(:name => '汤加', :full_name => '汤加王国')
  Country.find_by_code('tt').update_attributes(:name => '特立尼达和多巴哥', :full_name => '特立尼达和多巴哥共和国')
  Country.find_by_code('tn').update_attributes(:name => '突尼斯', :full_name => '突尼斯共和国')
  Country.find_by_code('tr').update_attributes(:name => '土耳其', :full_name => '土耳其共和国')
  Country.find_by_code('tm').update_attributes(:name => '土库曼斯坦')
  Country.find_by_code('tv').update_attributes(:name => '图瓦卢')
  Country.find_by_code('ug').update_attributes(:name => '乌干达', :full_name => '乌干达共和国')
  Country.find_by_code('ua').update_attributes(:name => '乌克兰')
  Country.find_by_code('ae').update_attributes(:name => '阿联酋', :full_name => '阿拉伯联合酋长国')
  Country.find_by_code('gb').update_attributes(:name => '英国', :full_name => '大不列颠及北爱尔兰联合王国')
  Country.find_by_code('uy').update_attributes(:name => '乌拉圭', :full_name => '乌拉圭东岸共和国')
  Country.find_by_code('uz').update_attributes(:name => '乌兹别克斯坦', :full_name => '乌兹别克斯坦共和国')
  Country.find_by_code('vu').update_attributes(:name => '瓦努阿图', :full_name => '瓦努阿图共和国')
  Country.find_by_code('va').update_attributes(:name => '梵蒂冈', :full_name => '梵蒂冈城国')
  Country.find_by_code('ve').update_attributes(:name => '委内瑞拉', :full_name => '委内瑞拉玻利瓦尔共和国')
  Country.find_by_code('vn').update_attributes(:name => '越南', :full_name => '越南社会主义共和国')
  Country.find_by_code('ye').update_attributes(:name => '也门', :full_name => '也门共和国')
  Country.find_by_code('zm').update_attributes(:name => '赞比亚', :full_name => '赞比亚共和国')
  Country.find_by_code('zw').update_attributes(:name => '津巴布韦', :full_name => '津巴布韦共和国')
end
